---
title: "Ctnnd2 PNN and PV Data Analysis"
author: "Gabi Sejourne and Grace Richardson"
date: "03/06/2025"
editor: visual 
execute: 
  echo: true 
editor_options: 
  chunk_output_type: inline
---

```{r}
#| label: packages and data:

#packages for statistical analysis
if(!require(lsmeans)){install.packages("lsmeans")}
if(!require(multcompView)){install.packages("multcompView")}
if(!require(dplyr)){install.packages("dplyr")}
if(!require(rcompanion)){install.packages("rcompanion")}
if(!require(rcompanion)){install.packages("ggprism")}

library(tidyverse)
library(stringr)
library(car)
library(FSA)
library(ggpubr)
library(ggbeeswarm)
library(ggprism)
```

```{r}
#| label: reading in CSV files

Image_data1 = read.csv("MOD_DATA/Summary_set1.csv")
Image_data2 = read.csv("MOD_DATA/Summary_set2and3.csv")
Decoder = read.csv("DATA/Decoder_all_sets.csv")
Image_data2 <- Image_data2 |>
  filter(GT != "HET")
```

```{r}
Image_data2 <- Image_data2 |>
  mutate(
  PV_cell_density = (`Green.Puncta.Count` / 1242095.4) * 1000,
  WFA_cell_density = (`Red.Puncta.Count` / 1242095.4) * 1000,
  Coloc_cell_density = (`Colocalized.Puncta.Count` /1242095.4) * 1000,
  single_pos_density = ((`Green.Puncta.Count` - `Colocalized.Puncta.Count`)/1242095.4) * 1000
  )

ReplicateAverages_PV <- Image_data2 |>
  group_by(GT, Age.P, Animal) |>
  summarise(PV_avg = mean(PV_cell_density))


# Calculates total averages
TotalAverages_PV <- ReplicateAverages_PV |>
  summarise(PV_avg_avg = mean(PV_avg))
TotalAverages_PV
```

```{r}
# PV statistics
modelPV = lm(PV_avg ~ GT,
           data = ReplicateAverages_PV)

Anova(modelPV,
      type = "II")

summary(modelPV)
```

```{r}
library(multcompView)
library(lsmeans)

leastsquare = lsmeans(modelPV,
                   pairwise ~ GT,
                   adjust="tukey")
leastsquare$contrasts

```

```{r}
library(DescTools)

DunnettTest(PV_avg ~ GT,
            data = ReplicateAverages_PV,
            control = "WT")
```

```{r}
library(dplyr)
library(ggplot2)
library(ggbeeswarm)
library(ggprism)

my_colors <- c("WT" = "dodgerblue", "KO" = "firebrick1")

# Set factor order first
Image_data2 <- Image_data2 |>
  mutate(GT = factor(GT, levels = c("WT", "KO")))

# Replicate (animal) averages within genotype
ReplicateAverages_PV <- Image_data2 |>
  group_by(GT, Animal) |>
  summarise(
    PV_avg = mean(PV_cell_density, na.rm = TRUE),
    .groups = "drop"
  )

# Total averages per genotype
TotalAverages_PV <- ReplicateAverages_PV |>
  group_by(GT) |>
  summarise(
    PV_avg_avg = mean(PV_avg, na.rm = TRUE),
    .groups = "drop"
  )

# Plot
superplot_PV <- ggplot() +
  geom_jitter(
    data = Image_data2,
    aes(x = GT, y = PV_cell_density, color = GT),
    width = 0.2,
    size = 2,
    alpha = 0.2
  ) +
  geom_col(
    data = TotalAverages_PV,
    aes(x = GT, y = PV_avg_avg, fill = GT),
    width = 0.4,
    alpha = 0.4
  ) +
  stat_summary(
    data = ReplicateAverages_PV,
    aes(x = GT, y = PV_avg),
    fun.data = mean_se,
    geom = "errorbar",
    width = 0.2,
    color = "black"
  ) +
  geom_point(
    data = ReplicateAverages_PV,
    aes(x = GT, y = PV_avg, color = GT),
    size = 2,
    alpha = 0.9
  ) +
  theme_minimal() +
  scale_color_manual(values = my_colors) +
  scale_fill_manual(values = my_colors) +
  labs(
    x = "",
    y = expression("PV+ cells (x" * 10^3 * "/mm"^2 * ")")
  ) +
  theme(
    legend.position = "none"
  )

ggsave(
  filename = "./Plots_all_sets/p30_Ctnnd2_superplot_pvalb.png",
  plot = superplot_PV,
  width = 3,
  height = 4,
  dpi = 300
)

superplot_PV
```

```{r}
Image_data2$GT <- factor(Image_data2$GT, levels = c("WT", "HET", "KO"))

ReplicateAverages_WFA <- Image_data2 |>
  group_by(Age.P, GT, Animal) |>
  summarise(WFA_avg = mean(WFA_cell_density))
ReplicateAverages_WFA

# Calculates total averages
TotalAverages_WFA <- ReplicateAverages_WFA |>
  summarise(WFA_avg_avg = mean(WFA_avg))
TotalAverages_WFA


```

```{r}
modelPNN = lm(WFA_avg ~ GT,
           data = ReplicateAverages_WFA)

Anova(modelPNN,
      type = "II")

summary(modelPNN)
```

```{r}
library(multcompView)
library(lsmeans)

leastsquare = lsmeans(modelPNN,
                   pairwise ~ GT,
                   adjust="tukey")

leastsquare
```

```{r}
library(DescTools)

DunnettTest(WFA_avg ~ GT,
            data = ReplicateAverages_WFA,
            control = "WT")
```

```{r}
# make p value dataframe based on results of lsmeans comparison

superplot_WFA <- ggplot() +
  geom_jitter(
    data = Image_data2,
    aes(x = GT, y = WFA_cell_density, color = GT),
    width = 0.2,
    size = 2,
    alpha = 0.2
  ) +
  geom_col(
    data = TotalAverages_WFA,
    aes(x = GT, y = WFA_avg_avg, fill = GT),
    width = 0.4,
    alpha = 0.4
  ) +
  stat_summary(
    data = ReplicateAverages_WFA,
    aes(x = GT, y = WFA_avg),
    fun.data = mean_se,
    geom = "errorbar",
    width = 0.2,
    color = "black"
  ) +
  geom_point(
    data = ReplicateAverages_WFA,
    aes(x = GT, y = WFA_avg, color = GT),
    size = 2,
    alpha = 0.9
  ) +
  scale_fill_manual(values = c("dodgerblue", "firebrick1")) +
  scale_color_manual(values = c("dodgerblue", "firebrick1")) +
  labs(
    title = "",
    x = "",
    y = expression("WFA+ cells (x" * 10^3 * "/mm"^2 * ")")
  ) +
  theme_minimal() +
  theme(legend.position = "none")

ggsave(
  filename = "./Plots_all_sets/p30_Ctnnd2_superplot_WFA.png",
  plot = superplot_WFA,
  width = 3,
  height = 4,
  dpi = 300
)

superplot_WFA
```

```{r}
#Calculates replicate averages
Image_data2$Genotype <- factor(Image_data2$GT, levels = c("WT", "HET", "KO"))
ReplicateAverages_double_pos <- Image_data2 |>
  group_by(Age.P, GT, Animal) |>
  summarise(double_pos_avg = mean(Coloc_cell_density))
ReplicateAverages_double_pos

# Calculates total averages
TotalAverages_double_pos <- ReplicateAverages_double_pos |>
  summarise(double_pos_avg_avg = mean(double_pos_avg))
TotalAverages_double_pos
```

```{r}
model_double_pos = lm(double_pos_avg ~ GT,
           data = ReplicateAverages_double_pos)

Anova(model_double_pos,
      type = "II")

summary(model_double_pos)
```

```{r}
library(multcompView)
library(lsmeans)

leastsquare = lsmeans(model_double_pos,
                   pairwise ~ GT,
                   adjust = "tukey")

leastsquare
```

```{r}
library(DescTools)

DunnettTest(`Colocalized.Puncta.Count` ~ GT,
            data = Image_data2,
            control = "WT")
```

```{r}

# make p value dataframe based on results of lsmeans comparison

superplot_double_pos <- ggplot() +
  geom_jitter(
    data = Image_data2,
    aes(x = GT, y = Coloc_cell_density, color = GT),
    width = 0.2,
    size = 2,
    alpha = 0.2
  ) +
  geom_col(
    data = TotalAverages_double_pos,
    aes(x = GT, y = double_pos_avg_avg, fill = GT),
    width = 0.4,
    alpha = 0.4
  ) +
  stat_summary(
    data = ReplicateAverages_double_pos,
    aes(x = GT, y = double_pos_avg),
    fun.data = mean_se,
    geom = "errorbar",
    width = 0.2,
    color = "black"
  ) +
  geom_point(
    data = ReplicateAverages_double_pos,
    aes(x = GT, y = double_pos_avg, color = GT),
    size = 2,
    alpha = 0.9
  ) +
  scale_color_manual(values = my_colors) +
  scale_fill_manual(values = my_colors) +
  labs(
    title = "",
    x = "",
    y = expression("PV+/WFA+ cells (x" * 10^3 * "/mm"^2 * ")")
  ) +
  theme_minimal() +
  theme(legend.position = "none")

ggsave(
  filename = "./Plots_all_sets/p30_Ctnnd2_superplot_double_pos.png",
  plot = superplot_double_pos,
  width = 3,
  height = 4,
  dpi = 300
)

superplot_double_pos
```

```{r}
Image_data2$single_pos <- Image_data2$`Green.Puncta.Count` -Image_data2$`Colocalized.Puncta.Count`

ReplicateAverages_single_pos <- Image_data2 |>
  group_by(Age.P, GT, Animal) |>
  summarise(single_pos_avg = mean(single_pos_density))
ReplicateAverages_single_pos

# Calculates total averages
TotalAverages_single_pos <- ReplicateAverages_single_pos |>
  summarise(single_pos_avg_avg = mean(single_pos_avg))
TotalAverages_single_pos
```

```{r}
model_single_pos = lm(single_pos_avg ~ GT,
           data = ReplicateAverages_single_pos)

Anova(model_single_pos,
      type = "II")

summary(model_single_pos)
```

```{r}
library(multcompView)
library(lsmeans)

leastsquare = lsmeans(model_single_pos,
                   pairwise ~ GT,
                   adjust = "tukey")

leastsquare
```

```{r}
library(DescTools)

DunnettTest(single_pos_avg ~ GT,
            data = ReplicateAverages_single_pos,
            control = "WT")
```

```{r}
# make p value dataframe based on results of lsmeans comparison with tukey posthoc

superplot_single_pos <- ggplot() +
  geom_jitter(
    data = Image_data2,
    aes(x = GT, y = single_pos_density, color = GT),
    width = 0.2,
    size = 2,
    alpha = 0.2
  ) +
  geom_col(
    data = TotalAverages_single_pos,
    aes(x = GT, y = single_pos_avg_avg, fill = GT),
    width = 0.4,
    alpha = 0.4
  ) +
  stat_summary(
    data = ReplicateAverages_single_pos,
    aes(x = GT, y = single_pos_avg),
    fun.data = mean_se,
    geom = "errorbar",
    width = 0.2,
    color = "black"
  ) +
  geom_point(
    data = ReplicateAverages_single_pos,
    aes(x = GT, y = single_pos_avg, color = GT),
    size = 2,
    alpha = 0.9
  ) +
  scale_color_manual(values = my_colors) +
  scale_fill_manual(values = my_colors) +
  labs(
    title = "",
    x = "",
    y = expression("PV+/WFA- cells (x" * 10^3 * "/mm"^2 * ")")
  ) +
  theme_minimal() +
  theme(legend.position = "none")

ggsave(
  filename = "./Plots_all_sets/p30_Ctnnd2_superplot_single_pos.png",
  plot = superplot_single_pos,
  width = 3,
  height = 4,
  dpi = 300
)

superplot_single_pos
```

```{r}
Image_data2$pct_double <-  100 * Image_data2$`Colocalized.Puncta.Count` / Image_data2$`Green.Puncta.Count`

ReplicateAverages_pct_double <- Image_data2 |>
  group_by(Age.P, GT, Animal) |>
  summarise(pct_double_avg = mean(pct_double))
ReplicateAverages_pct_double

# Calculates total averages
TotalAverages_pct_double <- ReplicateAverages_pct_double |>
  summarise(pct_double_avg_avg = mean(pct_double_avg))
TotalAverages_pct_double
```

```{r}
model_pct_double = lm(pct_double_avg ~ GT,
                      data = ReplicateAverages_pct_double)
Anova(model_pct_double,
      type = "II")

summary(model_pct_double)
```

```{r}
library(multcompView)
library(lsmeans)

leastsquare = lsmeans(model_pct_double,
                   pairwise ~ GT,
                   adjust = "tukey")

leastsquare
```

```{r}
library(DescTools)

DunnettTest(pct_double_avg ~ GT,
            data = ReplicateAverages_pct_double,
            control = "WT")
```

```{r}
# make p value dataframe based on results of lsmeans comparison with tukey posthoc

superplot_pct_double <- ggplot() +
  geom_jitter(
    data = Image_data2,
    aes(x = GT, y = pct_double, color = GT),
    width = 0.2,
    size = 2,
    alpha = 0.2
  ) +
  geom_col(
    data = TotalAverages_pct_double,
    aes(x = GT, y = pct_double_avg_avg, fill = GT),
    width = 0.4,
    alpha = 0.4
  ) +
  stat_summary(
    data = ReplicateAverages_pct_double,
    aes(x = GT, y = pct_double_avg),
    fun.data = mean_se,
    geom = "errorbar",
    width = 0.2,
    color = "black"
  ) +
  geom_point(
    data = ReplicateAverages_pct_double,
    aes(x = GT, y = pct_double_avg, color = GT),
    size = 2,
    alpha = 0.9
  ) +
  scale_color_manual(values = my_colors) +
  scale_fill_manual(values = my_colors) +
  labs(
    title = "",
    x = "",
    y = "% (PV+/PNN+) / PV+"
  ) +
  theme_minimal() +
  theme(legend.position = "none") +
  coord_cartesian(ylim = c(0, 100))

ggsave(
  filename = "./Plots_all_sets/p30_Ctnnd2_superplot_pct_double.png",
  plot = superplot_pct_double,
  width = 3,
  height = 4,
  dpi = 300
)

superplot_pct_double

```
